import { Course } from "./CourseCard";
import bannerTL21C from "@/assets/course-tl21c.jpg";
import bannerTL21C_C1 from "@/assets/tl21c-c1-banner.png";
import bannerHDPSG from "@/assets/course-hdpsg.png";
import bannerALICP from "@/assets/course-alicp.png";
import bannerPM from "@/assets/course-pm.jpg";
import bannerDSC from "@/assets/course-dsc.jpg";
import bannerELE from "@/assets/course-ele.jpg";
import bannerPGD from "@/assets/course-pgd.jpg";

// Subject accent palette (replaces previous college tags)
const accent = {
  Health: "bg-[#80BC00]/15 text-[#5a8a00]",
  Education: "bg-[#853275]/15 text-[#853275]",
  Computing: "bg-[#FFB600]/20 text-[#8a6300]",
  Business: "bg-[#0083C1]/15 text-[#0083C1]",
  Engineering: "bg-[#EE7623]/15 text-[#b85412]",
  Communication: "bg-[#8E1537]/15 text-[#8E1537]",
} as const;

export const sampleCourses: Course[] = [
  // Featured 1: Teaching and Learning for the 21st Century — Micro-credential parent
  {
    code: "TL21C-001",
    subject: "Education",
    title: "Teaching and Learning for the 21st Century",
    headline: "Lead the Future of Education — master AI, digital tools and sustainable teaching strategies.",
    desc: "Rethink your teaching practice with evidence-based pedagogy, purposeful technology integration, and the evolving role of AI in education.",
    type: "Micro-credential",
    delivery: "Online",
    duration: "5 hrs",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    isMicroCredential: true,
    subCourseCodes: ["TL21C-C1", "TL21C-C2", "TL21C-C3", "TL21C-C4", "TL21C-C5"],
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This Micro-credential is designed to help you rethink, refine and reimagine your approach to teaching in a rapidly evolving world.\n\nIt enables educators to develop the knowledge and skills to design purposeful, technology-enhanced learning experiences grounded in 21st century teaching principles and informed by the evolving role of artificial intelligence in education, to improve student learning and create sustainable educational impact.",
    outcomes: [
      "Integrate generative AI meaningfully into your classes",
      "Design 21st-century learning experiences",
      "Apply the 5 pillars to your teaching",
      "Choose technology based on learning goals, not trends",
      "Create lessons that have lasting, transferable impact",
    ],
    audience:
      "This Micro-credential is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    structure:
      "Teaching and Learning for the 21st Century is a 5-course Micro-credential delivered in a self-paced online learning environment, designed to equip educators with practical frameworks, digital strategies, and future-ready mindsets to transform teaching and learning for the modern world.\n\nEach course can be enrolled in individually, or completed as a full pathway.",
    howYouLearn:
      "You will learn through self-paced online modules, guided activities, reflective tasks, and applied scenarios drawn from contemporary classrooms. Each of the 5 courses is fully online and can be completed flexibly at your own pace.",
  },
  // TL21C sub-course 1
  {
    code: "TL21C-C1",
    subject: "Education",
    title: "Education in the Age of AI",
    headline: "Understanding Artificial Intelligence and its impact on teaching and learning",
    desc: "Examine the growing influence of AI on teaching and learning and develop the awareness, knowledge, and practical strategies needed to respond thoughtfully and effectively.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    parentCode: "TL21C-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course invites educators to examine the growing influence of AI on teaching and learning, and to develop the awareness, knowledge, and practical strategies needed to respond thoughtfully and effectively.\n\nYou will explore how AI is transforming not only the tools we use, but also the skills students need, the role of the instructor, and the very purpose of education itself, with the goal of creating learning experiences that remain meaningful, ethical, and future-ready.",
    outcomes: [
      "Evaluate the impact of AI on education, including its current uses, opportunities, challenges, and implications for teaching and learning",
      "Analyse ethical considerations and risks associated with AI in educational contexts, including responsible and appropriate use in teaching practice",
      "Design AI-enhanced learning experiences into classroom practice that support student success and reflect sound pedagogical principles",
      "Integrate AI and digital technologies with intention and purpose to support effective teaching and learning design",
      "Design classroom practices that utilise AI to support student success while adhering to sound pedagogical principles",
    ],
    audience:
      "This course is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Experience AI in Education" },
      { label: "Module 2", topic: "Making Sense of AI in Practice" },
      { label: "Module 3", topic: "Understanding AI in Education" },
      { label: "Module 4", topic: "Applying AI in Your Teaching Practice" },
    ],
  },
  // TL21C sub-course 2
  {
    code: "TL21C-C2",
    subject: "Education",
    title: "Teaching for the 21st Century",
    headline: "Exploring modern teaching approaches for today's learners",
    desc: "Explore how teaching and learning are evolving in response to digital transformation, changing learner expectations, and the demands of a rapidly changing world.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    parentCode: "TL21C-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course invites educators to explore how teaching and learning are evolving in response to digital transformation, changing learner expectations, and the demands of a rapidly changing world.\n\nYou will examine the shift from traditional, instructor-centered approaches toward more active, learner-centered experiences that foster collaboration, creativity, critical thinking, and adaptability, with the goal of creating engaging learning environments that prepare students for success in the 21st century.",
    outcomes: [
      "Describe characteristics of 21st century learning",
      "Apply learner-centered teaching strategies",
      "Identify approaches that support student engagement",
      "Explain the changing role of educators",
    ],
    audience:
      "This course is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "What does 21st Century Teaching look like?" },
      { label: "Module 2", topic: "Rethinking Your Teaching Practice" },
      { label: "Module 3", topic: "Frameworks for 21st Century Learning" },
      { label: "Module 4", topic: "Designing for 21st Century Learning" },
    ],
  },
  // TL21C sub-course 3
  {
    code: "TL21C-C3",
    subject: "Education",
    title: "The 5 Pillars of Teaching and Learning",
    headline: "A practical framework for effective and engaging learning experiences",
    desc: "Explore five essential pillars that support meaningful and effective learning experiences across applied learning, communication, relationships, classroom management and engagement.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    parentCode: "TL21C-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course invites educators to explore five essential pillars that support meaningful and effective learning experiences: applied and experiential learning, communication, student-teacher relationships, classroom management, and student engagement and motivation.\n\nYou will examine how these interconnected elements shape learner success and influence the quality of teaching and learning environments, with the goal of designing experiences that are engaging, inclusive, reflective, and impactful for diverse learners.",
    outcomes: [
      "Describe the 5 pillars framework",
      "Identify strategies to improve learner engagement",
      "Apply inclusive teaching practices",
      "Support reflection and collaboration in learning",
    ],
    audience:
      "This course is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Experiencing the Pillars in Action" },
      { label: "Module 2", topic: "Evaluating Your Strengths and Gaps" },
      { label: "Module 3", topic: "Understanding the Pillars" },
      { label: "Module 4", topic: "Strengthening Your Teaching Practice" },
    ],
  },
  // TL21C sub-course 4
  {
    code: "TL21C-C4",
    subject: "Education",
    title: "Using Technology with Purpose",
    headline: "Integrating technology intentionally to enhance learning",
    desc: "Rethink the role of technology in teaching and learning by focusing not on the tools themselves, but on the purpose behind their use.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    parentCode: "TL21C-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course invites educators to rethink the role of technology in teaching and learning by focusing not on the tools themselves, but on the purpose behind their use.\n\nYou will explore how digital technologies can support pedagogy, enhance engagement, and align with learning outcomes when used intentionally and meaningfully, with the goal of creating technology-enhanced learning experiences that are effective, learner-centered, and aligned with educational goals.",
    outcomes: [
      "Select technologies that support learning outcomes",
      "Apply principles of digital pedagogy",
      "Design simple technology-enhanced learning activities",
      "Evaluate the effectiveness of educational technologies",
    ],
    audience:
      "This course is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Exploring Technology in Action" },
      { label: "Module 2", topic: "Questioning Technology Use" },
      { label: "Module 3", topic: "Principles for Purposeful Integration" },
      { label: "Module 4", topic: "Designing with Technology" },
    ],
  },
  // TL21C sub-course 5
  {
    code: "TL21C-C5",
    subject: "Education",
    title: "Teaching for Sustainable Impact",
    headline: "Designing inclusive and future-focused learning experiences that last",
    desc: "Consider how teaching and learning can create lasting impact in an increasingly complex and changing world through sustainability, inclusion and lifelong learning.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Education,
    bannerImage: bannerTL21C,
    hasDetailPage: true,
    parentCode: "TL21C-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course invites educators to consider how teaching and learning can create lasting impact in an increasingly complex and changing world.\n\nYou will explore approaches that support sustainability, inclusion, adaptability, and lifelong learning, while examining how educators can design learning experiences that remain relevant, equitable, and future-focused, with the goal of building learning environments that empower learners today while preparing them for the challenges and opportunities of tomorrow.",
    outcomes: [
      "Explain principles of sustainable teaching and learning",
      "Identify strategies for inclusive learning design",
      "Support lifelong learning and adaptability",
      "Design learning experiences with long-term impact",
    ],
    audience:
      "This course is designed for university and college faculty, school teachers and instructional staff, corporate trainers and learning professionals, instructional designers and eLearning developers, academic leaders and education administrators, and graduate students interested in education and technology. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Understanding Impact in Education" },
      { label: "Module 2", topic: "Evaluating Long-Term Effectiveness" },
      { label: "Module 3", topic: "Principles of Sustainable Teaching" },
      { label: "Module 4", topic: "Designing for Lasting Impact" },
    ],
  },
  // Featured 2: Health Information Governance — Micro-credential parent
  {
    code: "HDPSG-001",
    subject: "Health",
    title: "Health Information Governance",
    headline: "Mastering Security, Governance, and Innovation in Digital Health",
    desc: "Equip yourself with the critical skills to navigate the complex digital health landscape, from privacy law and software evaluation to data integrity and AI innovation.",
    type: "Micro-credential",
    delivery: "Online",
    duration: "4 hrs",
    accent: accent.Health,
    bannerImage: bannerHDPSG,
    hasDetailPage: true,
    isMicroCredential: true,
    subCourseCodes: ["HIG-C1", "HIG-C2", "HIG-C3", "HIG-C4"],
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This comprehensive 4-course Micro-credential is designed to equip healthcare professionals with the critical skills needed to navigate the complex digital health landscape.\n\nFrom privacy law and software evaluation to data integrity and AI innovation, learners will gain actionable insights to lead governance initiatives in modern clinical environments.",
    outcomes: [
      "Classify health data by sensitivity and apply global privacy frameworks",
      "Evaluate healthcare software and optimise clinical workflows",
      "Apply data governance principles to ensure operational integrity",
      "Analyse the impact of emerging technologies like AI and wearables on patient care",
    ],
    audience:
      "This Micro-credential is designed for healthcare administrators, IT professionals, Clinical Informatics specialists, policy analysts, healthcare students seeking specialised certification, and career shifters. No advanced technical background is required.",
    structure:
      "Health Information Governance is a 4-course Micro-credential delivered in a self-paced online learning environment.\n\nEach course can be enrolled in individually, or completed as a full pathway.",
    howYouLearn:
      "You will learn through self-paced online modules, practical examples, guided activities, and applied case-based scenarios drawn from healthcare settings. Each of the 4 courses is fully online and can be completed flexibly at your own pace.",
  },
  // HIG sub-course 1
  {
    code: "HIG-C1",
    subject: "Health",
    title: "The Privacy Shield",
    headline: "Protecting Patient Data in a Borderless Digital World",
    desc: "Explore the ethical and legal foundations of health data privacy, from privacy versus security to global legislative standards and breach prevention.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Health,
    bannerImage: bannerHDPSG,
    hasDetailPage: true,
    parentCode: "HDPSG-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "Learners will explore the ethical and legal foundations of health data privacy. The course covers the critical differences between privacy and security, global legislative standards, and strategies for safeguarding data against breaches.",
    outcomes: [
      "Classify data based on sensitivity",
      "Identify global privacy protection steps and legislative standards",
      "Differentiate between privacy and security in a healthcare context",
      "Apply safeguarding strategies to protect against breaches",
    ],
    audience:
      "This course is designed for administrative staff and IT security leads. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "The Privacy Landscape (Ethics, Privacy vs Security, GDPR/HIPAA)" },
      { label: "Module 2", topic: "Safeguarding Data (Classification, Security Protocols, Case Study: Data Breach)" },
    ],
  },
  // HIG sub-course 2
  {
    code: "HIG-C2",
    subject: "Health",
    title: "Navigating the Digital Hospital",
    headline: "Evaluating Technology for Better Clinical Outcomes",
    desc: "Build a toolkit for evaluating Healthcare Information Systems and ensuring digital infrastructure supports, rather than hinders, patient care.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Health,
    bannerImage: bannerHDPSG,
    hasDetailPage: true,
    parentCode: "HDPSG-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course provides a toolkit for evaluating Healthcare Information Systems (HIS). Learners will study digital infrastructure, clinical workflows, and the interoperability between systems to ensure technology supports, rather than hinders, patient care.",
    outcomes: [
      "Evaluate healthcare software against clear selection criteria",
      "Understand digital workflows in clinical settings",
      "Assess interoperability between healthcare systems",
      "Apply UX principles to healthcare technology evaluation",
    ],
    audience:
      "This course is designed for clinical managers, IT procurement teams, and workflow analysts. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "The Digital Infrastructure (HIS/EHR, Workflows, Interoperability)" },
      { label: "Module 2", topic: "The Evaluation Toolkit (Selection Criteria, UX in Healthcare, Dashboard Activity)" },
    ],
  },
  // HIG sub-course 3
  {
    code: "HIG-C3",
    subject: "Health",
    title: "The Data Rulebook",
    headline: "Ensuring the Accuracy and Lifecycle Integrity of Health Data",
    desc: "Examine the roles, responsibilities, and frameworks required to maintain high-quality health data across the full data lifecycle.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Health,
    bannerImage: bannerHDPSG,
    hasDetailPage: true,
    parentCode: "HDPSG-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "Focusing on the why and how of information governance, this course details the roles, responsibilities, and frameworks required to maintain high-quality data. Learners will study the data lifecycle from creation to secure destruction.",
    outcomes: [
      "Apply data governance principles to ensure information is accurate and safe",
      "Describe key information governance roles and responsibilities",
      "Assess the health of an organisation's data",
      "Manage the data lifecycle from creation to secure destruction",
    ],
    audience:
      "This course is designed for data stewards, health information managers, and compliance officers. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Governance Frameworks (IG Fundamentals, Roles, Assessing Data Health)" },
      { label: "Module 2", topic: "Data Integrity & Lifecycle (Quality, Data Ops, Governance Culture)" },
    ],
  },
  // HIG sub-course 4
  {
    code: "HIG-C4",
    subject: "Health",
    title: "Healthcare 2.0",
    headline: "Leading Innovation in the Era of AI and Remote Care",
    desc: "Explore the frontier of health technology, from AI and predictive analytics to the governance of remote patient monitoring and telemedicine.",
    type: "Professional",
    delivery: "Online",
    duration: "1 hr",
    accent: accent.Health,
    bannerImage: bannerHDPSG,
    hasDetailPage: true,
    parentCode: "HDPSG-001",
    price: 100,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "Explore the frontier of health technology. This course covers the basics of AI and machine learning, the ethics of predictive analytics, and the governance requirements for remote patient monitoring and telemedicine.",
    outcomes: [
      "Recognise emerging trends in health technology",
      "Analyse the impact of new technology on health data",
      "Evaluate the ethics and bias of predictive analytics in healthcare",
      "Apply governance requirements to remote patient monitoring and telemedicine",
    ],
    audience:
      "This course is designed for healthcare innovators, clinical leads, and health-tech entrepreneurs. No advanced technical background is required.",
    syllabus: [
      { label: "Module 1", topic: "Intelligence in Healthcare (AI/ML Basics, Predictive Analytics, Ethics/Bias)" },
      { label: "Module 2", topic: "The Future of Remote Care (Wearables, Telemedicine, Capstone: Your Future in Health-Tech)" },
    ],
  },
  // Project Management Essentials (General Education)
  {
    code: "PME-GE-001",
    subject: "Professional Skills",
    title: "Project Management Essentials",
    desc: "Build practical project management skills you can apply at work, in study, and in everyday life, from planning through to successful completion.",
    type: "Professional",
    delivery: "Online",
    duration: "5–6 hrs",
    accent: accent.Business,
    bannerImage: bannerPM,
    hasDetailPage: true,
    price: 450,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course introduces learners to the essential concepts and practical skills of project management in everyday contexts. It explores how projects differ from routine activities and guides learners through the key stages of managing a project, from planning to completion.\n\nLearners will develop the ability to organise tasks, manage time and resources, solve problems, and achieve goals effectively. The course is designed to be accessible to all learners, regardless of their background, and highlights how project management skills can be applied in work, study, and personal life.",
    outcomes: [
      "Identify the key characteristics of a project and distinguish it from routine tasks",
      "Apply basic project management steps to plan and complete a task or goal",
      "Analyse common challenges in projects such as time, resources, and risks",
      "Select appropriate tools and strategies to organise and manage tasks",
      "Evaluate the success of a project and suggest ways to improve outcomes",
    ],
    audience:
      "This course is designed for learners from any background who want to build practical project management skills they can apply in work, study, and personal life.",
    structure:
      "This fully online course is organised into focused units that introduce project management step by step, from understanding what makes a project to planning, managing, and reviewing it.\n\nEach unit combines clear explanations with relatable examples and practical activities, making the content accessible to learners with no prior experience.",
    howYouLearn:
      "You will learn through self-paced online modules, guided activities, and practical examples drawn from everyday work, study, and personal contexts. The course is fully online and can be completed flexibly at your own pace.",
    syllabus: [
      { label: "Module 1 · 1 hr", topic: "What is a project? Key characteristics and everyday examples" },
      { label: "Module 2 · 1 hr", topic: "Planning a project: goals, tasks, and timelines" },
      { label: "Module 3 · 1 hr", topic: "Managing time, resources, and risks" },
      { label: "Module 4 · 1 hr", topic: "Tools and strategies to organise and track work" },
      { label: "Module 5 · 1–2 hrs", topic: "Reviewing outcomes and improving future projects" },
    ],
    launchUrl: "https://d2l.udst.edu.qa/d2l/home/187828",
  },
  // Featured 4: Adaptive Leadership and Interprofessional Collaborative Practice
  {
    code: "ALICP-001",
    subject: "Health",
    title: "Adaptive Leadership and Interprofessional Collaborative Practice",
    desc: "Build leadership skills for interprofessional healthcare teams and support person-centred care in complex clinical settings.",
    type: "Professional",
    delivery: "Online",
    duration: "5 hrs",
    accent: accent.Health,
    bannerImage: bannerALICP,
    hasDetailPage: true,
    price: 950,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course aims to assist learners to learn the art of adaptive leadership for clinical leadership and practice within interprofessional teams to enhance person-centred health care.\n\nThere is a focus on interprofessional competencies and the principles, tools, and techniques of adaptive leadership to mobilise, motivate, organise, and focus interprofessional healthcare teams to navigate the complexities of change for effective health care.\n\nOffered through eUDST, the University of Doha for Science & Technology's online learning platform, this course supports professionals who want to strengthen their leadership capability and contribute more effectively within collaborative healthcare environments.",
    outcomes: [
      "Compare theories of leadership",
      "Apply interprofessional competencies to support person-centred care in clinical practice",
      "Analyse the practice of leadership for addressing technical and adaptive challenges",
      "Analyse personal and organisational barriers to change",
      "Examine adaptive leadership and its relevance to person-centred health care",
    ],
    audience:
      "This course is designed for healthcare professionals and practitioners who want to strengthen their leadership skills and work more effectively within interprofessional teams.",
    structure:
      "This fully online course is organised into a series of interactive units that guide learners through the principles and practice of adaptive leadership in interprofessional healthcare settings.\n\nEach unit includes short modules, practical examples, and applied learning activities that connect leadership theory to real clinical practice. The course is designed for flexible, self-paced study, allowing learners to progress through the content in a clear and structured way while building knowledge step by step.",
    howYouLearn:
      "You will learn through interactive online modules, real-world healthcare scenarios, reflective activities, and practical examples. The course encourages active engagement with leadership concepts and helps you apply them to collaborative healthcare practice and person-centred care.",
    syllabus: [
      { label: "Module 1 · 1 hr", topic: "Foundational theories of leadership in healthcare" },
      { label: "Module 2 · 1 hr", topic: "Interprofessional competencies and person-centred care" },
      { label: "Module 3 · 1 hr", topic: "Technical and adaptive challenges in clinical settings" },
      { label: "Module 4 · 1 hr", topic: "Personal and organisational barriers to change" },
      { label: "Module 5 · 1 hr", topic: "Adaptive leadership in interprofessional practice" },
    ],
    launchUrl: "https://d2l.udst.edu.qa/d2l/le/lessons/187827/lessons/3747206",
  },
  // Other detailed courses
  {
    code: "DSC-CCIT-001",
    subject: "Computing",
    title: "Discrete Structures for Computing",
    desc: "Build the mathematical foundations behind computing, from logic and proofs to graphs, trees and discrete probability.",
    type: "Academic",
    delivery: "Blended",
    duration: "45 hrs",
    accent: accent.Computing,
    bannerImage: bannerDSC,
    hasDetailPage: true,
    price: 1850,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "This course introduces the fundamental discrete structures required for computing. Learners are encouraged to analyse problems related to discrete structures and find correct solutions backed by clear and precise proof.\n\nTopics include logic and proving methods; sets, functions, sequences and summations; numeral systems; logic gates and simple combinational circuits; induction; counting tools and discrete probability; relations, graphs and trees.",
    outcomes: [
      "Apply logic to prove simple theorems",
      "Describe basic structures for mathematics such as sets, functions, sequences, and sums",
      "Practice Boolean algebra in the context of simple combinational circuits",
      "Deduce properties using mathematical induction",
      "Calculate discrete probability using counting techniques",
      "Define useful structures for computing such as relations, graphs, and trees",
    ],
    audience:
      "This course is designed for computing students and aspiring software professionals who want a strong mathematical foundation for further study in computer science, software engineering, and information technology.",
    structure:
      "Delivered through blended learning, the course combines structured online modules with applied learning activities. Learners progress through a clear sequence of topics, building from logic and proof techniques to advanced discrete structures used across computing.",
    howYouLearn:
      "You will learn through online lessons, worked examples, problem sets, and applied exercises. Blended delivery supports independent study while providing structured opportunities to apply concepts to computing problems.",
    syllabus: [
      { label: "Module 1 · 7 hrs", topic: "Logic, propositions and methods of proof" },
      { label: "Module 2 · 7 hrs", topic: "Sets, functions, sequences and summations" },
      { label: "Module 3 · 7 hrs", topic: "Numeral systems, Boolean algebra and combinational circuits" },
      { label: "Module 4 · 7 hrs", topic: "Mathematical induction and recursive reasoning" },
      { label: "Module 5 · 8 hrs", topic: "Counting techniques and discrete probability" },
      { label: "Module 6 · 9 hrs", topic: "Relations, graphs and trees" },
    ],
    launchUrl: "https://d2l.udst.edu.qa/d2l/le/lessons/133782/units/3013381",
  },
  {
    code: "ELE-CGE-001",
    subject: "Business",
    title: "Experiential Learning and Entrepreneurship",
    desc: "Build the academic, collaborative and entrepreneurial skills needed to thrive at university and in your future career.",
    type: "Academic",
    delivery: "Blended",
    duration: "45 hrs",
    accent: accent.Business,
    bannerImage: bannerELE,
    hasDetailPage: true,
    price: 1850,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "In today's fast-paced and ever-changing global landscape, the ability to innovate, work effectively in teams, and lead with vision is more crucial than ever.\n\nThis introductory hybrid course provides learners with a broad understanding of the critical skills needed to succeed in both their academic and future professional careers. Through a blend of theoretical knowledge and practical application, learners are introduced to a range of strategies for academic success, innovation, and entrepreneurship.",
    outcomes: [
      "Demonstrate effective learning strategies for a university environment",
      "Develop critical thinking and problem-solving skills to address diverse situations and challenges",
      "Show effective group dynamics and strategies in group project work at the university level",
      "Demonstrate an understanding of an entrepreneurial mindset and innovative thinking skill",
    ],
    audience:
      "This course is designed for new and aspiring university learners, as well as early-career professionals who want to strengthen their academic skills, collaborative practice, and entrepreneurial thinking.",
    structure:
      "Delivered through blended learning, the course combines structured online modules with collaborative activities and applied tasks. Learners move through a clear sequence of topics covering academic success, teamwork, problem solving, and entrepreneurship.",
    howYouLearn:
      "You will learn through online modules, group-based activities, applied case studies, and reflective exercises. Blended delivery supports both independent study and collaborative practice.",
    syllabus: [
      { label: "Module 1 · 9 hrs", topic: "Foundations for university success and effective learning strategies" },
      { label: "Module 2 · 9 hrs", topic: "Critical thinking and problem solving in real-world contexts" },
      { label: "Module 3 · 9 hrs", topic: "Group dynamics, collaboration and team-based projects" },
      { label: "Module 4 · 9 hrs", topic: "Innovation, creativity and the entrepreneurial mindset" },
      { label: "Module 5 · 9 hrs", topic: "Applied entrepreneurship and project showcase" },
    ],
    launchUrl: "https://d2l.udst.edu.qa/d2l/le/lessons/133782/units/3013381",
  },
  {
    code: "PGD-INIC-001",
    subject: "Health",
    title: "Post-Graduate Diploma in Interprofessional Neonatal Intensive Care (PGD INIC)",
    desc: "Advance your NICU practice with a stackable, interprofessional pathway covering leadership, applied therapeutics and immersive clinical practicum.",
    type: "Micro-credential",
    delivery: "Blended",
    duration: "18 months",
    accent: accent.Health,
    bannerImage: bannerPGD,
    hasDetailPage: true,
    price: 14500,
    currency: "QAR",
    language: "en",
    startDate: "Enrol anytime",
    longDesc:
      "Delivered in partnership with Sidra Medicine, the Post-Graduate Diploma in Interprofessional Neonatal Intensive Care is a unique educational pathway to upskill healthcare professionals in the Neonatal Intensive Care Unit (NICU).\n\nThis Micro-Credential Series is designed for NICU nurses seeking to advance their clinical expertise, leadership capacity, and evidence-based practice across the continuum of neonatal care. The pathway integrates critical competencies in leadership, research appraisal, and advanced therapeutics for both preterm and term infants, culminating in immersive clinical practice within high-acuity neonatal environments.",
    outcomes: [
      "Lead and manage change in complex neonatal intensive care environments",
      "Critically appraise research and apply evidence-based practice in NICU care",
      "Apply advanced therapeutic interventions for critically ill preterm infants",
      "Apply advanced therapeutic interventions for critically ill term infants",
      "Demonstrate advanced clinical decision-making in interprofessional NICU teams",
      "Integrate leadership, research and clinical expertise through immersive practicum",
    ],
    audience:
      "This pathway is designed for NICU nurses and interprofessional healthcare team members seeking to advance their clinical expertise, leadership capability, and evidence-based practice across the full continuum of neonatal intensive care.",
    structure:
      "The PGD INIC programme consists of four stackable Micro-Credentials, delivered through blended learning over 18 months.\n\nMC 1: Critical Competencies for Managing and Leading Change, supporting NICU nurses to enhance leadership and evidence-based decision-making.\n\nMC 2: Applied Therapeutics for Critically Ill Preterm Infants, deepening clinical expertise in care of preterm infants.\n\nMC 3: Applied Therapeutics for Critically Ill Term Infants, deepening clinical expertise in care of term infants.\n\nMC 4: Advanced Practices for the Critically Ill Infants, an immersive, hands-on clinical practicum integrating advanced clinical skills, real-time decision-making and collaborative interprofessional practice.",
    howYouLearn:
      "You will learn through blended delivery combining online theory, applied case-based learning, and immersive clinical practicum within high-acuity neonatal environments. The programme emphasises interprofessional collaboration and real-time decision-making in complex NICU contexts.",
    syllabus: [
      { label: "MC 1", topic: "Critical Competencies for Managing and Leading Change" },
      { label: "MC 2", topic: "Applied Therapeutics for Critically Ill Preterm Infants" },
      { label: "MC 3", topic: "Applied Therapeutics for Critically Ill Term Infants" },
      { label: "MC 4", topic: "Advanced Practices for the Critically Ill Infants, Clinical Practicum" },
    ],
    launchUrl: "https://d2l.udst.edu.qa/d2l/le/lessons/144413/units/3115857",
  },

  // ───────────────────────────────────────────────
  // Upcoming courses (coming soon)
  // ───────────────────────────────────────────────

  // College of Business
  {
    code: "ECON-2010",
    subject: "Business",
    title: "Business Economics",
    desc: "Core economic principles applied to real business decisions, with instructor Jaywant Michael.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Business,
    isPlaceholder: true,
  },
  {
    code: "MGMT-3035",
    subject: "Business",
    title: "Business Ethics",
    desc: "Explore ethical decision-making in modern organisations, with instructor David Booker.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Business,
    isPlaceholder: true,
  },

  // College of Health Sciences
  {
    code: "HSOH-2050",
    subject: "Health",
    title: "Epidemiology",
    desc: "Foundations of epidemiology and population health, with Dr Musa Harona Moda.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Health,
    isPlaceholder: true,
  },
  {
    code: "NURS-4104",
    subject: "Health",
    title: "Adaptive Leadership and Clinical Management",
    desc: "Develop adaptive leadership and clinical management skills, with Dr Ayat.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Health,
    isPlaceholder: true,
  },

  // College of Computing and IT
  {
    code: "DSAI-3203",
    subject: "Computing",
    title: "Fundamentals of AI",
    desc: "An introduction to the core concepts and techniques of artificial intelligence, with Dr Bekir.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Computing,
    isPlaceholder: true,
  },
  {
    code: "DACS-2201",
    subject: "Computing",
    title: "Introduction to Cybersecurity",
    desc: "Build foundational knowledge of cybersecurity principles and practice, with Dr Abdullatif.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Computing,
    isPlaceholder: true,
  },

  // College of Engineering
  {
    code: "AEMA-4100",
    subject: "Engineering",
    title: "Project Management and Leadership",
    desc: "Project management and leadership for engineering contexts, with Luay Hussein.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Engineering,
    isPlaceholder: true,
  },
  {
    code: "AEEP-4100",
    subject: "Engineering",
    title: "Project Management",
    desc: "Project management foundations for engineering professionals, with Dr Ahmad Awad.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Engineering,
    isPlaceholder: true,
  },

  // College of General Education
  {
    code: "SCIE-1002",
    subject: "Education",
    title: "General Science",
    desc: "An accessible introduction to general science, with instructor Majid Ibraheem.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Education,
    isPlaceholder: true,
  },
  {
    code: "GARC-2002",
    subject: "General Education",
    title: "Globalisation and the Environment",
    desc: "Explore the complex links between globalisation and the environment through ecological, social, political, cultural, and economic perspectives, with instructor Mariam Alisi.",
    type: "Academic",
    delivery: "Blended",
    duration: "Coming soon",
    accent: accent.Education,
    isPlaceholder: true,
    longDesc:
      "It is important that students understand the intricate nexus between globalisation and the environment as many of our contemporary challenges relate to issues stemming from this complex relationship.\n\nThis interdisciplinary course examines multiple perspectives on ecological, social, political, cultural, and economic drivers. Students perform a multi-level analysis of diverse topics such as international cooperation, the global economy, and science and technology in the context of Qatar.\n\nStudents are expected to plan and execute a small project related to one of the primary case studies that will be explored throughout the semester.",
  },

  // ───────────────────────────────────────────────
  // Academic Blended Courses (UDST academics only)
  // ───────────────────────────────────────────────

  // College of Business
  {
    code: "HCMT3002",
    subject: "Business",
    title: "Health Information Governance",
    desc: "Explore the balance between access to individualised healthcare data and the privacy, security and governance demands of modern health systems.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Business,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Healthcare data is often personal and therefore subject to increasing legislation across the globe. Data must be protected, but it is also essential in the effective treatment of individual patients.\n\nThis course explores the complex balance between access to individualised data and the need for data privacy. In addition, students examine the value of using broader data trends in a society to recognise emerging healthcare and treatment issues.\n\nThis is a complex and fast-moving area which is increasingly at the cutting edge of emerging information technologies.",
    outcomes: [
      "Classify the types of healthcare data according to their sensitivity",
      "Evaluate the software available to healthcare providers",
      "Apply data security protocols in healthcare",
      "Analyse best practices of data governance in healthcare",
      "Analyse trends and innovations in healthcare data management",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "IT-supported workflows in healthcare" },
      { label: "Module 2", topic: "Introduction to healthcare information systems" },
      { label: "Module 3", topic: "Data classification" },
      { label: "Module 4", topic: "Data inventory and data ops" },
      { label: "Module 5", topic: "Data governance assessment" },
      { label: "Module 6", topic: "Fundamentals of health information governance" },
      { label: "Module 7", topic: "Data governance framework" },
      { label: "Module 8", topic: "Roles in information governance" },
      { label: "Module 9", topic: "Data privacy protection" },
      { label: "Module 10", topic: "Securing information systems" },
      { label: "Module 11", topic: "Emerging technologies and trends in data governance" },
    ],
  },

  // College of Computing and IT
  {
    code: "DACS2101",
    subject: "Computing",
    title: "Discrete Structures",
    desc: "Build the mathematical foundations behind computing through logic, proofs, Boolean algebra, induction, counting, and graphs.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Computing,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Discrete structures are fundamental to the understanding of many computing principles, from algorithms analysis to digital logic circuits design.\n\nIn this course, students analyse problems related to discrete structures and find correct solutions backed by clear and precise proof. Topics covered include logic and proving methods, basic structures from sets to graphs and trees, logic gates and simple combinational circuits, induction, counting tools, and discrete probability.\n\nThrough a combination of theory-based lectures and hands-on lab experiences, students gain insights into the multiple uses of discrete structures in computing.",
    outcomes: [
      "Apply logic to prove simple theorems",
      "Describe basic structures for mathematics such as sets, functions, sequences and sums",
      "Practise Boolean algebra in the context of simple combinational circuits",
      "Deduce properties using mathematical induction",
      "Calculate discrete probability using counting techniques",
      "Define useful structures for computing such as relations, graphs and trees",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Propositional logic" },
      { label: "Module 2", topic: "Predicate logic" },
      { label: "Module 3", topic: "Proofs" },
      { label: "Module 4", topic: "Numeral systems" },
      { label: "Module 5", topic: "Boolean algebra" },
      { label: "Module 6", topic: "Logic gates and digital circuits" },
      { label: "Module 7", topic: "Sets" },
      { label: "Module 8", topic: "Functions" },
      { label: "Module 9", topic: "Sequences and summations" },
      { label: "Module 10", topic: "Mathematical induction" },
      { label: "Module 11", topic: "Strong induction" },
      { label: "Module 12", topic: "Counting techniques" },
      { label: "Module 13", topic: "Probability" },
      { label: "Module 14", topic: "Relations, graphs and trees" },
    ],
  },

  // College of Engineering and Technology
  {
    code: "AEMA4100",
    subject: "Engineering",
    title: "Project Management",
    desc: "A systematic introduction to project management for engineers, covering planning, tools, leadership and team-based delivery.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Engineering,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "All engineers, in general, would need proper management systems to execute the required tasks and duties. This course provides a systematic and thorough introduction to all aspects of project management.\n\nProjects are an increasingly important aspect of engineering. The course underlines the importance of understanding the relationship between projects and the strategic goals of an organisation. Through presentations and lectures, students are able to implement proper management styles to successfully manage projects from start to finish.\n\nIt emphasises that project management is a professional discipline with its own tools, body of knowledge, and skills.",
    outcomes: [
      "Analyse the importance of project management",
      "Analyse initiatives that would need to be categorised as a project",
      "Develop project plans and proper documentation, including Gantt charts and project costings",
      "Assess different projects' risks and their mitigation through efficient project management, leadership and team building",
      "Compare different project management styles and cultural diversity",
      "Elaborate on the importance of leadership in successful project management",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Project management strategies for success" },
      { label: "Module 2", topic: "Introductory project management principles for engineers" },
      { label: "Module 3", topic: "Fundamentals of PMBOK: structure, concepts and application" },
      { label: "Module 4", topic: "Applying project management tools for integrated engineering projects" },
      { label: "Module 5", topic: "Project ecosystems and stages of group development" },
      { label: "Module 6", topic: "Mastering the five phases of project management (IPECC)" },
    ],
  },

  // College of General Education
  {
    code: "EFFL1003",
    subject: "Education",
    title: "Experiential Learning and Entrepreneurship",
    desc: "Develop the academic, collaborative and entrepreneurial skills needed to thrive at university and in your future career.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Education,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "In today's fast-paced and ever-changing global landscape, the ability to innovate, work effectively in teams, and lead with vision is more crucial than ever.\n\nThis introductory hybrid course provides students with a broad understanding of the critical skills needed to succeed in both their academic and future professional careers. Through a blend of theoretical knowledge and practical application, students are introduced to a range of strategies for academic success, innovation, and entrepreneurship.",
    outcomes: [
      "Demonstrate effective learning strategies for a university environment",
      "Develop critical thinking and problem-solving skills to address diverse situations and challenges",
      "Show effective group dynamics and strategies in group project work at the university level",
      "Demonstrate an understanding of an entrepreneurial mindset and innovative thinking skills",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Overview of experiential learning and entrepreneurship" },
      { label: "Module 2", topic: "Strategies for student success" },
      { label: "Module 3", topic: "Academic success planning" },
      { label: "Module 4", topic: "Working in teams" },
      { label: "Module 5", topic: "Critical thinking and problem solving" },
      { label: "Module 6", topic: "Introduction to entrepreneurship" },
      { label: "Module 7", topic: "Design thinking and innovation" },
      { label: "Module 8", topic: "Understanding the market and conducting a needs analysis" },
      { label: "Module 9", topic: "Ideation, research and development" },
      { label: "Module 10", topic: "Project planning" },
    ],
  },
  {
    code: "SSHA1004",
    subject: "Education",
    title: "Ethical Reasoning",
    desc: "Apply ethical theories and moral philosophy to contemporary problems through critical thinking and applied case studies.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Education,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Ethical reasoning is a type of critical thinking that uses ethical principles and frameworks to ensure sound decision-making and effective problem solving.\n\nThis course introduces the theories, methods, and practical problems of ethics and moral philosophy. Topics covered include the nature of ethical reasoning, moral theories of notable philosophers, the concepts of right and wrong, and moral responsibility.\n\nThrough a variety of assignments, quizzes, and hybrid online learning, the course is designed to help students develop their critical thinking capabilities from an ethical perspective and to better understand various moral problems in today's world.",
    outcomes: [
      "Identify and explain basic theories and concepts related to the study of ethics and moral philosophy",
      "Identify key figures in moral philosophy and explain the relevance of their ideas and methods in ethical reasoning",
      "Compare and contrast key philosophical standpoints on morality, ethical reasoning and issues of right and wrong",
      "Demonstrate an understanding of the relevance of moral philosophy and ethical reasoning for contemporary ethical problems facing societies and individuals in everyday life and in the context of modern technology",
      "Apply the concepts of ethical reasoning theories such as Virtue Theory, Stoicism, Deontology, Utilitarianism and Contractarianism to practical situations, scenarios and case studies",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Introduction to ethics and philosophy" },
      { label: "Module 2", topic: "Ethical theories and dilemmas" },
      { label: "Module 3", topic: "Virtue ethics" },
      { label: "Module 4", topic: "Stoicism" },
      { label: "Module 5", topic: "Dialectical interview" },
      { label: "Module 6", topic: "Social contract" },
      { label: "Module 7", topic: "Deontology" },
      { label: "Module 8", topic: "Applying principles of deontology" },
      { label: "Module 9", topic: "Utilitarianism" },
      { label: "Module 10", topic: "Review" },
      { label: "Module 11", topic: "Film analysis" },
    ],
  },

  // College of Health Sciences
  {
    code: "NUMW2210",
    subject: "Health",
    title: "Perspectives of Complex Maternal Health",
    desc: "Apply midwifery concepts and evidence to provide woman- and family-centred care across complex acute, chronic and emergency maternity scenarios.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Health,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Students apply midwifery concepts, theories and evidence in the provision of woman, person and family-centred care for maternity persons experiencing select complex acute, chronic, and emergency mental and physical health challenges that pre-exist or present for the first time during pregnancy and birth.\n\nStudents learn how to escalate care and to provide interim provisional emergency care while awaiting the arrival of health professionals.",
    outcomes: [
      "Demonstrate a basic understanding of core professional, ethical and legal principles underpinning midwifery care to women experiencing complex acute, chronic and emergency health challenges",
      "Demonstrate a basic understanding of midwifery philosophy, theories and knowledge to guide woman- and person-centred midwifery care",
      "Demonstrate a basic understanding of evidence to guide midwifery care across complex maternity scenarios",
      "Demonstrate basic competence in critical and clinical thinking in the care of women with complex challenges",
      "Demonstrate intermediate competence in developmentally and culturally appropriate communication with women, families and the wider healthcare team",
      "Routinely display personal responsibility for own learning and midwifery practice",
      "Routinely engage in self-reflection and self-evaluation when providing midwifery care",
      "Demonstrate intermediate competence in the use of healthcare and information technologies that support midwifery practice",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Maternal and neonatal mortality" },
      { label: "Module 2", topic: "Circulatory and haemolytic function" },
      { label: "Module 3", topic: "Cardiovascular conditions and hypertensive disorders in pregnancy" },
      { label: "Module 4", topic: "Autoimmune disorders and metabolic conditions" },
      { label: "Module 5", topic: "Musculoskeletal and gastrointestinal disorders" },
      { label: "Module 6", topic: "Endocrine disorders and gestational diabetes" },
      { label: "Module 7", topic: "Thromboembolic disorders in childbearing" },
      { label: "Module 8", topic: "Renal and hepatic disorders" },
      { label: "Module 9", topic: "Neurological and psychological disorders" },
      { label: "Module 10", topic: "Respiratory conditions, infectious diseases and skin disorders" },
    ],
  },
  {
    code: "HSPA4223",
    subject: "Health",
    title: "Paramedicine Patient Management III",
    desc: "Develop advanced paramedic decision-making across immunology, paediatrics, toxicology, environmental and high-altitude emergencies.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Health,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Paramedics must demonstrate independent critical thinking and decision-making skills during medical emergencies.\n\nThis is the third of three courses which provide students with the knowledge and skills necessary to incorporate advanced clinical decision-making into the provision of holistic care for a wide variety of disorders.\n\nIn this part, students formulate care plans for disorders related to haematology and immunology, communicable diseases, toxic exposures, exposure to adverse environments, and high altitude and diving incidents, as well as emergencies involving paediatric patients.",
    outcomes: [
      "Formulate, implement, evaluate and revise care plans for the management of immunological emergencies",
      "Formulate, implement, evaluate and revise care plans for the management of paediatric emergencies",
      "Formulate, implement, evaluate and revise care plans for the management of communicable diseases",
      "Formulate, implement, evaluate and revise care plans for the management of disorders of the eyes, ears, nose and throat",
      "Formulate, implement, evaluate and revise care plans for the management of toxicological emergencies",
      "Formulate, implement, evaluate and revise care plans for the management of environmental emergencies",
      "Formulate, implement, evaluate and revise care plans for the management of high altitude and diving emergencies",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Haematology and immune system" },
      { label: "Module 2", topic: "Paediatric emergencies" },
      { label: "Module 3", topic: "Communicable diseases" },
      { label: "Module 4", topic: "EENT disorders" },
      { label: "Module 5", topic: "Toxicology" },
      { label: "Module 6", topic: "Environmental emergencies" },
      { label: "Module 7", topic: "Aviation and diving emergencies" },
    ],
  },
  {
    code: "HSPT2204",
    subject: "Health",
    title: "Non-Sterile Compounding",
    desc: "Build essential pharmacy technician skills in non-sterile compounding through hands-on preparation, calculations and laboratory practice.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Health,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Compounding of pharmaceuticals is an essential skill for a pharmacy technician and technologist. This course focuses on preparation and the essential techniques involved in non-sterile compounding.\n\nStudents follow and process compounded prescriptions with zero tolerance for errors. Course content includes the preparation of ointments, creams, solutions, suspensions and capsules through extemporaneous methods.\n\nStudents are also introduced to the history of compounding, pharmaceutical forms and preparation, packaging, and maintaining the pharmaceutical elegance of all prepared products. The course also offers a review of pharmaceutical calculations related to extemporaneous compounding and percentage of error. Learning takes place through lectures, practical activities and hands-on training in a fully equipped non-sterile compounding laboratory.",
    outcomes: [
      "Apply WHMIS in the workplace",
      "Apply compounding principles in the preparation of extemporaneous compounds",
      "Demonstrate proper technique of measuring, mixing and packaging solid and liquid compounds",
      "Calculate accurately to measure compounding ingredients, including using an aliquot, and determine the percentage of error of measurement",
      "Demonstrate proper use of compounding equipment",
      "Maintain proper documentation of preparing extemporaneous and limited batch compounds",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "Introduction to compounding and WHMIS" },
      { label: "Module 2", topic: "Compounding principles" },
      { label: "Module 3", topic: "Compounding equipment" },
      { label: "Module 4", topic: "Percentage of error" },
      { label: "Module 5", topic: "Compounding ingredients" },
      { label: "Module 6", topic: "Extemporaneous capsules" },
      { label: "Module 7", topic: "Drug dilution and aliquot" },
    ],
  },
  {
    code: "HSRT2300",
    subject: "Health",
    title: "Airway Management",
    desc: "Develop core respiratory therapy airway management skills through equipment principles and applied laboratory practice.",
    type: "Academic",
    delivery: "Blended",
    duration: "Semester",
    accent: accent.Health,
    hasDetailPage: true,
    academicOnly: true,
    language: "en",
    longDesc:
      "Airway management is a crucial skill that enables a respiratory therapist to support patients requiring airway assistance.\n\nIn this course, students explore the use of various airway management techniques, related equipment and associated therapies. Primary emphasis is on the principles of operation of the various types of equipment utilised in airway management within respiratory therapy.\n\nA variety of lectures and practical laboratory exercises are used to gain the necessary knowledge, skills and abilities to work in a clinical environment.",
    outcomes: [
      "Manage the airway using a variety of devices and techniques",
      "Apply manual ventilation via BVM and adjuncts",
      "Apply suction therapy",
    ],
    syllabus: [
      { label: "Module 0", topic: "Welcome and Introduction" },
      { label: "Module 1", topic: "OPA, NPA and LMA" },
      { label: "Module 2", topic: "Manual resuscitators" },
      { label: "Module 3", topic: "Intubation" },
      { label: "Module 4", topic: "Suctioning" },
      { label: "Module 5", topic: "Extubation" },
      { label: "Module 6", topic: "Special airways and equipment" },
      { label: "Module 7", topic: "Difficult airway" },
      { label: "Module 8", topic: "Tracheostomy" },
      { label: "Module 9", topic: "NG tubes and chest drainage units" },
    ],
  },
];
